# CC := /home/dungnt98/f1c100s/licheepi_nano_sdk/buildroot-2021.02.3/buildroot-2021.02.3/output/host/usr/bin/arm-linux-cc
CC := gcc

all:
	$(CC) main.c -v -o test -lpthread -lpaho-mqtt3c
clean:
	rm test
